services:
  db:
    container_name: tolerance
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: tolerance
        MYSQL_USER: root
        MYSQL_PASSWORD: password
    volumes:
      - db:/data/mysql
    ports:
      - "1234:3306"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:
